name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths:
      - nintendo.shop.backend/** 
  pull_request:
    branches: [ "main" ]
    paths:
      - nintendo.shop.backend/** 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -P no-db-tests --file nintendo.shop.backend/pom.xml
